### PR TITLE
Initial pull request for comments and feedback

### PR DESCRIPTION
**Pull request by camkego**
Alexandre,
This is the first PR for your feedback and comments.
Please let me know any suggestions or improvements you recommend.
To summarize:

- Moved generated files from SharpDX.MediaFoundation/Generated/DirectX/*.cs to SharpDX.MediaFoundation/DirectX/Hand.Generated
- Added refs to SharpDX.Direct3D9 SharpDX.Mathematics inside SharpDX.MediaFoundation.csproj
- Removed SharpDX.MediaFoundation/DirectX/Mapping.xml (mistake?)
- Fixedup RawBool and Rectangle inside generated code
- Left in the new necessary call* functions, but commented out uneeded funcs
- Tested with my code which works on 2.6.3, these changes allow my code to now run on the 3.0.x base

### CODE REVIEW

**Comment by camkego** [comment]
Yeah, I see something broke with appveyor, I can duplicate the issue with msbuild from the command line, I am working to see if I can fix the issue.  I will report back here, later.

**Comment by camkego** [comment]
It seems the issue is adding the reference to Direct3D9 to MediaFoundation is what is causing the issue. 
They are using different frameworks, and the build fails with that reference. (Although the F5 build works.)  I presume it is the non-desktop build that is failing.

There are a lot of Direct3D9 inside both SharpDX.MediaFoundation/DirectX/Hand.Generated/*.cs, and SharpDX.MediaFoundation/DirectX/*.cs, so I am not sure how this can be done without referencing Direct3D9.

Any suggestions?  I will continue later to see if I can understand better what is going on, and what options might exist.
Thank you

**Comment by xoofx** [comment]
you need to use conditional in csproj to avoid referencing these files in StoreApp build. Similar to [this](https://github.com/sharpdx/SharpDX/blob/e7fcf95345da1f6c8dcbf5e73ec8781d75359fc1/Source/SharpDX.MediaFoundation/SharpDX.MediaFoundation.csproj#L11) but check for `Desktop` for `SharpDXPlatform`

**Comment by camkego** [comment]
xoofx,
Okay, everything seems to be compiling.
I looked at [c6d8e45](https://github.com/sharpdx/SharpDX/commit/c6d8e457a3c4b9c4af6b0bfc41817e45601e2787), but nothing jumped out at me which should be included, but I am not sure what I am looking for.
I also wonder if MSDNDoc.zip should go in the .gitignore

What questions can I answer or improvements can I make?

Thanks for guiding me through to this point.

**Comment by xoofx** [comment]
Thanks a lot for this work! It should help a few folks looking for Direct3D10 to be back.

**Pull request merged**
