### PR TITLE
Improve Direct2D and DirectWrite

### PR DESCRIPTION
**Pull request by andrewst**

### CODE REVIEW

**Comment by xoofx** [comment]
Thanks a lot for this!

**Comment by xoofx** [comment]
btw @andrewst I will probably try to release a new version of SharpDX Sunday or early next week, as I'm not sure I will have enough time in the coming weeks (moving back to France, holidays...etc.)
So let me know if you have anything in the pipe worth waiting.
Thanks!

**Comment by andrewst** [comment]
hi @xoofx 
I don't have new changes

**Comment by andrewst** [comment]
hi @xoofx 
What plans release a new version?
I think we may make release, and next step update windows SDK.
Thanks!

**Pull request merged**
