### PR TITLE
Add ARM and x86 profiles for use with Net.Native

### PR DESCRIPTION
**Pull request by nkast**
Having ARM/x86 binaries is required for working with the current release of Net.Native.
http://blogs.msdn.com/b/dotnet/archive/tags/dotnetnative/

### CODE REVIEW

**Comment by xoofx** [comment]
I'm closing this pull-request as the new 3.0.0 has changed lots of things in the build process. We will have to investigate how to support this correctly. (I would prefer for example to just run a binary patch on existing assemblies just to change the x86/x64 platform instead...)

**Comment by nkast** [comment]
Cool. Maybe wait for final VS2015.
Hopefully Net.Native will compile from MSIL now that they have it for all 3 platforms. Otherwise it means that packing win10 appx has to build and contain your code x3.

**Comment by nkast** [comment]
That won't be necessary. I just tested an app with CTP6 and only the executable needs to target a specific platform. Referenced assemblies can be 'ANY CPU'.

**Comment by xoofx** [comment]
That's great!

**Pull request closed without merging**
