### PR TITLE
Some new math functions

### PR DESCRIPTION
**Pull request by mrvux**
Hello, just a small pull request since I use those as extension methods almost everywhere, just thought this would benefit everyone:

* Abs for Vector2 / Vector3
* Some properties for bounding box (size/ center)

Thanks 
Julien

### CODE REVIEW

**Comment by bdachev** [comment]
Out of curiosity why do you calculate Center that way but not (max+min)*0.5?

**Comment by mrvux** [comment]
@bdachev Good point indeed, updated it now.

**Comment by manofstick** [comment]
@mrvux / @bdachev 

Not sure if it matters - but the previous way (i.e. min + (max-min)*.5) would have avoided overflow... But maybe that's just an academic point that would never occur in reality... Famous last words?

**Comment by xoofx** [comment]
Thanks, sorry for the delay (the (min+max)/2 blocked me, but after reading some paper, it is not a huge matter for floats...)

**Pull request merged**
