### PR TITLE
Update maping on Windows 10 Creators Update SDK 15063

### PR DESCRIPTION
**Pull request by andrewst**

### CODE REVIEW

**Comment by xoofx** [comment]
Looks like appveyor does not have Windows 10 SDK C++ installed, so I will have to wait to merge this PR until it is supported there.

I have logged an [issue on appveyor github](https://github.com/appveyor/ci/issues/1485)

**Comment by jkoritzinsky** [comment]
You should also update line 62 in Source/Mapping.xml to be

```
#define NTDDI_VERSION NTDDI_WIN10_RS2
```

That will ensure that all of the APIs are included for the mappings.

**Comment by andrewst** [comment]
Thanks @jkoritzinsky, I will fix this.

**Comment by andrewst** [comment]
Hi @xoofx. I finished, please looking.

**Comment by xoofx** [comment]
Thanks a lot for this!

**Pull request merged**
