### PR TITLE
Update to Windows 10 Anniversary Update - October 2016 Update (10.0.14393.0)

### LINKED ISSUE #811: Update to latest SDK version (10.0.14393.0)
Is it possible to update mapping to SDK version 10.0.14393.0 which came with latest VS update and release a nuget package?

### PR DESCRIPTION
**Pull request by amerkoleci**
Fixes #811

### CODE REVIEW

**Comment by amerkoleci** [comment]
All should be fine now, you can merge if you want.

Thanks

**Comment by QuantumDeveloper** [comment]
@amerkoleci  Cool. You are a mapping master :)
+100 to your karma

**Comment by xoofx** [comment]
@amerkoleci  Thanks a lot!

I would like to avoid copying `wincrypt.h`, so you can workaround this by adding a `#define SORTPP_PASS` in top level [Mapping.xml in the include_prolog section](https://github.com/sharpdx/SharpDX/blob/2d97c1857e6bd2f5c741f50fb6e2d98cab536552/Source/Mapping.xml#L43) to avoid compilation error. 

After could you rebase to remove wincrypt.h from the commits?

**Comment by amerkoleci** [comment]
@xoofx will do so later and commit in my branch, just dont merge now.

Thanks

**Comment by amerkoleci** [comment]
Should be fine now, you can merge if you want :)

**Comment by QuantumDeveloper** [comment]
Cool! Thanks!
@xoofx  
How soon could you release new version to nuget?

**Pull request merged**
