### PR TITLE
Adding Direct3D11On12 Support in Direct3D11

### PR DESCRIPTION
**Pull request by curin**
Added support for Direct3D11On12 in the Direct3D11 library as suggested by @xoofx . Removed the old mapping in Drect3d12 which was unused.

There does exist an unresolved problem, but I'm not sure what's causing it as the program just crashes. The code below always crashes with no error when I attempt to create a bitmap from a wrappedresource. This code is entirely based off of a directx12 sample. Just so you know this is an unresolved problem, and as I'm not getting any error feedback therefore I'm not sure what to make of it.

```C#
_fact2D = (new SharpDX.Direct2D1.Factory2(SharpDX.Direct2D1.FactoryType.MultiThreaded, SharpDX.Direct2D1.DebugLevel.Error)).QueryInterface<Factory2D>();
_dev11 = Device11.CreateFromDirect3D12(_dev, SharpDX.Direct3D11.DeviceCreationFlags.BgraSupport | SharpDX.Direct3D11.DeviceCreationFlags.Debug, null, _adapt, _queue);
// Query for the adapter and more advanced DXGI objects.
_dev11On12 = _dev11.QueryInterface<Device11On12>();
_devDXGI = _dev11On12.QueryInterface<SharpDX.DXGI.Device1>();

// Get the default Direct2D device and create a context.
_dev2D = new Device2D(_fact2D, _devDXGI);
_dev2DContext = new Device2DContext(_dev2D, SharpDX.Direct2D1.DeviceContextOptions.None);

_dev2DContext.PrimitiveBlend = SharpDX.Direct2D1.PrimitiveBlend.SourceOver;
_factWrite = new FactoryWrite(SharpDX.DirectWrite.FactoryType.Shared);

_properties = new BitmapProperties1(_format, _fact2D.DesktopDpi.Width, _fact2D.DesktopDpi.Width, SharpDX.Direct2D1.BitmapOptions.Target | SharpDX.Direct2D1.BitmapOptions.CannotDraw);

Surface _tempSurface;
for (int n = 0; n < FRAMECOUNT; n++)
{
        _rtv[n] = _chain.GetBackBuffer<Resource>(n);
        _dev.CreateRenderTargetView(_rtv[n], null, _cpuHandle);

        _dev11On12.CreateWrappedResource(_rtv[n], _resourceFlags, (int)ResourceStates.RenderTarget, (int)ResourceStates.Present, typeof(Resource11).GUID, out _wrappedBackBuffers[n]);
        _tempSurface = _wrappedBackBuffers[n].QueryInterface<Surface>();

        //Crashes on next line
        _targs[n] = new Bitmap1(_dev2DContext, _tempSurface, _properties);
        _cpuHandle += _rtvDescSize;
}
```

### CODE REVIEW

**Comment by curin** [comment]
update on the bug described above. Error text is given when the Direct2D.Factory2 is created with DebugLevel.None rather than DebugLevel.Error. DebugLevel.Information leads to the same lack of response.

The error being generated is an invalid parameter. I'm still investigating what parameter is causing the problem, but no luck so far

**Comment by curin** [comment]
found the problem. When creating your bitmap the pixelformat needs to be using the Format.Unknown and AlphaMode.Premultiplied. This led to a successful run

**Comment by Mayhem50** [comment]
What have you put to your _resourceFlags field ?

**Comment by curin** [comment]
Sorry for not getting back to this earlier. As for the specifics of the code I'm not really sure anymore as I no longer have this code. Resource11 is a typedef for d3d11 resource. I'm not sure what I had set for resourceFlags, I believe it was Shared. All things considered I haven't done much with D3D11on12 in the past year at all, since it isn't recommended by the Nvidia and AMD.

**Pull request merged**
