### PR TITLE
Update dependencies

### LINKED ISSUE #1035: ISwapChainPanelNative, ISwapChainBackgroundPanelNative disappear
Seams that due to recent binding generator tool change thoose 2 interfaces disappeared.

@jkoritzinsky Any thoughts?

### LINKED ISSUE #1036: [XAudio2] CreateMasteringVoice throws InvalidOperationException
...when accessing the ``Value`` property of a nullable object without checking if it ``HasValue``.
Seems like a codegen issue.
image

Version used: 4.1.0

### LINKED ISSUE #1037: [RawInput] SharpDX.RawInput.Device.GetDevices throws "System.NullReferenceException".
With 4.1.0 update this method throws an exception at anywhere and anytime. I thought it is on my end. But I create a new empty project from Windows Forms template and add only two references to SharpDX and SharpDX.RawInput. I wrote just one line (VB.NET):
`Public my_value As List(Of SharpDX.RawInput.DeviceInfo) = SharpDX.RawInput.Device.GetDevices`
Guess what... on 4.0.1 its perfect!

### LINKED ISSUE #1044: TextFormat.[TextAlignment,TextLayout] -> SetTextAlignment,SetTextLayout
TextFormat used to have TextAlignment and TextLayout as get, set properties, but now has been separated into SetTextAlignment and SetTextLayout methods. Is this intentional or an unintended side effect of automation?

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Update SharpGenTools and MSBuild.Sdk.Extras.

Fix #1044 
Fix #1037 
Fix #1036 
Fix #1035

### CODE REVIEW

**Comment by xoofx** [comment]
Will first publish a preview package to make some diffs with https://www.fuget.org, if you can help me checking we haven't any regression compare to pre 4.0.x

**Comment by xoofx** [comment]
And oops sorry, forgot to say thank you! 😉

**Comment by xoofx** [comment]
So starting to look at the diff for example XAudio2: https://www.fuget.org/packages/SharpDX.XAudio2/4.2.0-ci259/lib/netstandard1.1/diff/4.0.1/   Max/Min was previously remapped to Maximum/Minimum.

**Comment by xoofx** [comment]
Quite a good chunk of ResultCode disappeared from SharpDX.Direct2D1 https://www.fuget.org/packages/SharpDX.Direct2D1/4.2.0-ci259/lib/netstandard1.1/diff/4.0.1/

**Comment by jkoritzinsky** [comment]
It looks like the main differences from 4.0.1 are naming things like that and #1028. Only other difference I've seen is better property generation. Can you file an issue for the naming differences?

**Comment by xoofx** [comment]
Same for Direct3D11 https://www.fuget.org/packages/SharpDX.Direct3D11/4.2.0-ci259/lib/netstandard1.1/diff/4.0.1/ 

In previous codegen there was a special handling of short names to expand them, haven't checked how/if it is handled by SharpGenTools?

**Comment by jkoritzinsky** [comment]
That should be handled the same as before. I have unit tests for it too. I'll take a look and see if I can repro the naming issues.

**Comment by amerkoleci** [comment]
GetFrequencyRatio and Set are methods instead of props

**Comment by jkoritzinsky** [comment]
SetFrequencyRatio doesn't correctly fit the form for a property, so that one should be manually re-added IMO.

**Comment by jkoritzinsky** [comment]
Can you open an issue on SharpGenTools/SharpGenTools with the naming issues? I can't work on it at the moment but will take a look later.

**Pull request merged**
